<a href="https://colab.research.google.com/github/banuben/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.2

In [4]:
mydataset = {
'cars': ["BMW", "Volvo", "Ford"],
'counts': [3, 7, 2]
}
df = pd.DataFrame (mydataset)
print (df)

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2

In [ ]:
df.head()  #deafault 5rows

In [14]:
df.tail()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.describe(include='all') #numerical counts only

In [ ]:
df.iloc[2] #call data by index

In [ ]:
df.loc[2, "cars"]   #index, from(label) by column

In [ ]:
df[df["counts"] > 3]

In [ ]:
df.mean(numeric_only=True)

In [ ]:
df["counts"].mean()

In [ ]:
df.sum()

In [ ]:
df.min()

In [ ]:
df.max()

In [ ]:
df.median(numeric_only=True)

In [ ]:
df.count()

In [ ]:
df.std(numeric_only=True)

In [5]:
data_with_missing = {
      "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford" ],
      "counts": [3, 7, None, 8, 1, 9, None]
}
df_missing = pd.DataFrame (data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [7]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [8]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [ ]:
df_missing.dropna(subset="counts")

In [ ]:
df.missing.fillna()

In [15]:
df = pd.read_csv("/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df = pd.read_json("Titanic-Dataset.json")

df.head()

In [ ]:

df = pd.read_excel("test.xlsx")

df.tail()

In [ ]:
df.to_excel("test.xlsx")

In [ ]:

cars = pd.Series(["BMW", "Tesla", "Ferrari"])

print(cars)

In [ ]:
cars_series = data_with_missing ['cars']
print (cars_series)