<a href="https://colab.research.google.com/github/banuben/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("StudentsPerformance.csv")

print("Dataset shape (rows. columns):", df.shape)
print("Column name:", df.columns.tolist())
print("First 5 rows:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types:")
print(df.dtypes)

print("Missing values:")
print(df.isnull().sum())

Dataset shape (rows. columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
Summary statistics:
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
Data types:
gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object
Missing values:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [7]:
print("Average score by columns:")
df[["math score", "reading score", "writing score"]].mean()

Average score by columns:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [8]:
print("Maximum score by subjects:")
df[["math score", "reading score", "writing score"]].max()

Maximum score by subjects:

math score       100
reading score    100
writing score    100
dtype: int64

In [9]:
print("Minimum score by subjects:")
df[["math score", "reading score", "writing score"]].min()

Minimum score by subjects:

math score        0
reading score    17
writing score    10
dtype: int64

In [10]:
# Correlation
print("Correlation matrix:")
df[["math score", "reading score", "writing score"]].corr()

Correlation matrix:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [12]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
# df["pass/fail"] = np.where(df["average score"] >= 60, "Pass", "Fail")
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [15]:
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("Average scores by test preparation course:")
print(test_prep_group)

# Gender-based average
gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("Average scores by gender:")
print(gender_avg)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass/fail rate:")
print(pass_rate)

Average scores by test preparation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
Average scores by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
Pass/fail rate:
passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64

In [17]:
# Convert scores to Numpy array
scores = df[["math score", "reading score", "writing score"]].values

# Mean, Std Deviatian
print("Numpy Mean:"), np.mean(scores, axis=0)
print("Numpy Std:"), np.std(scores, axis=0)

# Z-score (normalize)
z_scores = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (Normalized numbers):")
print(z_scores[:5])

Numpy Mean:
Numpy Std:
Z-scores (Normalized numbers):
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]

In [18]:
# How many students scored above 90 average?
top_scorers = np.sum(df["average score"] > 90)
print("Number of students with average score above 90:", top_scorers)
# How many fails?
failed = df[df["passed"] == "No"]
print("Failed from exams:", len(failed))

Number of students with average score above 90: 50
Failed from exams: 103